#!/usr/bin/env python3
"""Copy agentrust-capture-core into each engine's ``_vendor`` directory.

The engines are invoked by shell hooks at session start, by absolute path, before
anything is installed. So the core cannot be a plain runtime dependency: a user who
installs the Claude Code plugin and nothing else must still get drift detection.
Each engine therefore prefers the installed package and falls back to a pinned
vendored copy.

That leaves the copies free to drift, which is the failure this whole exercise is
meant to end. So the copies are generated, never hand-edited, and CI asserts they
match the package byte for byte.

    python scripts/sync_vendored_core.py           # write the copies
    python scripts/sync_vendored_core.py --check   # verify, exit 1 on drift
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "packages" / "agentrust-capture-core" / "src" / "agentrust_capture_core"

#: Engines that vendor the core, as directories that will each hold
#: ``_vendor/agentrust_capture_core``.
ENGINES = (
    REPO / "claude-code" / "engine",
    REPO / "plugins" / "agentrust-codex" / "engine",
    REPO / "scheduled-agents" / "engine",
)

HEADER = """# Generated by scripts/sync_vendored_core.py. Do not edit.
#
# Pinned copy of agentrust-capture-core, used when the package is not installed.
# The engines run from shell hooks before anything is installed, so this fallback
# is what makes drift detection work on a bare plugin install. Edit
# packages/agentrust-capture-core and re-run the sync script; CI fails if this
# copy and the package disagree.
"""


def _targets() -> list[Path]:
    return [engine / "_vendor" / "agentrust_capture_core" for engine in ENGINES]


def _source_files() -> list[Path]:
    return sorted(SOURCE.glob("*.py"))


def write() -> int:
    for target in _targets():
        target.mkdir(parents=True, exist_ok=True)
        for existing in target.glob("*.py"):
            existing.unlink()
        for module in _source_files():
            shutil.copy2(module, target / module.name)
        (target / "VENDORED.md").write_text(HEADER, encoding="utf-8")
        print("wrote %s (%d modules)" % (target.relative_to(REPO), len(_source_files())))
    return 0


def check() -> int:
    expected = {module.name for module in _source_files()}
    failures: list[str] = []
    for target in _targets():
        if not target.is_dir():
            failures.append("%s is missing; run scripts/sync_vendored_core.py"
                            % target.relative_to(REPO))
            continue
        found = {module.name for module in target.glob("*.py")}
        for extra in sorted(found - expected):
            failures.append("%s/%s is not in the package" % (target.relative_to(REPO), extra))
        for missing in sorted(expected - found):
            failures.append("%s/%s is missing" % (target.relative_to(REPO), missing))
        for name in sorted(expected & found):
            if not filecmp.cmp(SOURCE / name, target / name, shallow=False):
                failures.append("%s/%s differs from the package"
                                % (target.relative_to(REPO), name))
    if failures:
        print("Vendored core is out of sync:", file=sys.stderr)
        for line in failures:
            print("  - %s" % line, file=sys.stderr)
        print("\nRun: python scripts/sync_vendored_core.py", file=sys.stderr)
        return 1
    print("vendored core matches the package in %d engine(s)" % len(_targets()))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                       help="verify the copies match, without writing")
    args = parser.parse_args()
    if not SOURCE.is_dir():
        print("package source not found at %s" % SOURCE, file=sys.stderr)
        return 1
    return check() if args.check else write()


if __name__ == "__main__":
    sys.exit(main())
