"""AuthorityDelegationV1 chain verification tests.

Every chain here comes from the committed fixtures in
``fixtures/delegation-chain/``, regenerated byte for byte by ``generate.py``
from published seeds, verified at the fixed ``reference_time`` in
``meta.json`` so the result is the same on every run. Every scenario changes
exactly one thing about the resolver or the expected reference, never the
chain content itself, and asserts the state, the failure code and the
member index together, so a result is attributed rather than assumed.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

from delegation_verify import (
    DELEGATION_REF_MISMATCH,
    INDETERMINATE,
    INVALID,
    STATES,
    UNSUPPORTED,
    VALID,
    verify_delegation_authority,
)

FIXTURE_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "delegation-chain"

FIXTURE_SHA256 = {
    "records.json": "4e599f3644ca8f9e399038e0d8357eaf3fdf88c4aed3f007b64751e7f98103ba",
    "keys.json": "c7517f7979e787d1ceb2c6702a5226ba763e1f2e50ece153157af68519029e12",
    "meta.json": "47bc9d2bb5eb5aaf6285d0d66999e959afb8e89413f57aa8d14bfbc08e65ab27",
}


def _fixture(name: str) -> dict:
    return json.loads((FIXTURE_DIR / name).read_text())


def test_fixtures_are_the_committed_bytes() -> None:
    for name, digest in FIXTURE_SHA256.items():
        assert hashlib.sha256((FIXTURE_DIR / name).read_bytes()).hexdigest() == digest


RECORDS = _fixture("records.json")
KEYS = _fixture("keys.json")["pinned"]
META = _fixture("meta.json")
NOW = META["reference_time"]


def _resolve_key(_issuer, verification_method, _issued_at):
    return KEYS.get(verification_method)


def _trust_root(record: dict) -> bool:
    return record["issuer"] in META["trusted_roots"]


def _always_active(_delegation: dict) -> str:
    return "active"


def _revoked_only(delegation_id: str):
    def resolve(delegation: dict) -> str:
        return "revoked" if delegation["delegation_id"] == delegation_id else "active"

    return resolve


SIMPLE_CHAIN = [RECORDS["simple_root"], RECORDS["simple_leaf"]]


def test_states_never_include_valid_by_accident() -> None:
    assert STATES == (VALID, INVALID, INDETERMINATE, UNSUPPORTED)


# 1. valid active chain


def test_valid_active_chain() -> None:
    result = verify_delegation_authority(
        SIMPLE_CHAIN,
        expected_delegation_ref=META["simple_leaf_delegation_ref"],
        now=NOW,
        resolve_verification_key=_resolve_key,
        trust_root=_trust_root,
        resolve_revocation=_always_active,
    )
    assert result.state == VALID
    assert result.valid
    assert result.failures == ()


# 2. revoked ancestor


def test_revoked_ancestor_is_invalid_at_its_index() -> None:
    result = verify_delegation_authority(
        SIMPLE_CHAIN,
        expected_delegation_ref=META["simple_leaf_delegation_ref"],
        now=NOW,
        resolve_verification_key=_resolve_key,
        trust_root=_trust_root,
        resolve_revocation=_revoked_only(RECORDS["simple_root"]["delegation_id"]),
    )
    assert result.state == INVALID
    assert not result.valid
    assert len(result.failures) == 1
    assert result.failures[0].code == "REVOKED"
    assert result.failures[0].index == 0


# 3. revocation state unavailable or stale


def test_revocation_state_unavailable_is_indeterminate() -> None:
    def stale_at_leaf(delegation: dict) -> str:
        if delegation["delegation_id"] == RECORDS["simple_leaf"]["delegation_id"]:
            return "stale"
        return "active"

    result = verify_delegation_authority(
        SIMPLE_CHAIN,
        expected_delegation_ref=META["simple_leaf_delegation_ref"],
        now=NOW,
        resolve_verification_key=_resolve_key,
        trust_root=_trust_root,
        resolve_revocation=stale_at_leaf,
    )
    assert result.state == INDETERMINATE
    assert not result.valid
    assert result.failures[0].code == "REVOCATION_UNKNOWN"
    assert result.failures[0].index == 1


def test_indeterminate_is_never_collapsed_to_valid() -> None:
    result = verify_delegation_authority(
        SIMPLE_CHAIN,
        expected_delegation_ref=META["simple_leaf_delegation_ref"],
        now=NOW,
        resolve_verification_key=_resolve_key,
        trust_root=_trust_root,
        resolve_revocation=lambda _d: "unknown",
    )
    assert result.state == INDETERMINATE
    assert result.valid is False


# 4. expected delegation_ref mismatch


def test_expected_delegation_ref_mismatch() -> None:
    wrong_ref = "sha256:" + "0" * 64
    result = verify_delegation_authority(
        SIMPLE_CHAIN,
        expected_delegation_ref=wrong_ref,
        now=NOW,
        resolve_verification_key=_resolve_key,
        trust_root=_trust_root,
        resolve_revocation=_always_active,
    )
    assert result.state == INVALID
    assert result.failures[0].code == DELEGATION_REF_MISMATCH
    assert result.failures[0].index == len(SIMPLE_CHAIN) - 1


def test_delegation_ref_mismatch_is_checked_before_the_chain_would_otherwise_verify() -> None:
    # The chain itself is fully valid. Only the caller's expectation is wrong.
    # The mismatch must still be what is reported, not a "valid" result that
    # ignores what the caller asked about.
    wrong_ref = RECORDS["simple_root"]["delegation_id"]  # a real id, just not the leaf's
    result = verify_delegation_authority(
        SIMPLE_CHAIN,
        expected_delegation_ref=wrong_ref,
        now=NOW,
        resolve_verification_key=_resolve_key,
        trust_root=_trust_root,
        resolve_revocation=_always_active,
    )
    assert result.state == INVALID
    assert result.failures[0].code == DELEGATION_REF_MISMATCH


# 5. sponsor handover: OLD invalid, NEW valid, same agent-x identity


def test_sponsor_handover_old_chain_is_invalid_after_employee_revocation() -> None:
    old_chain = [RECORDS["old_root"], RECORDS["old_leaf_agent_x"]]
    result = verify_delegation_authority(
        old_chain,
        expected_delegation_ref=META["old_leaf_agent_x_delegation_ref"],
        now=NOW,
        resolve_verification_key=_resolve_key,
        trust_root=_trust_root,
        resolve_revocation=_revoked_only(RECORDS["old_root"]["delegation_id"]),
    )
    assert result.state == INVALID
    assert result.failures[0].code == "REVOKED"
    assert result.failures[0].index == 0


def test_sponsor_handover_new_chain_is_valid_independently() -> None:
    new_chain = [RECORDS["new_root"], RECORDS["new_leaf_agent_x"]]
    result = verify_delegation_authority(
        new_chain,
        expected_delegation_ref=META["new_leaf_agent_x_delegation_ref"],
        now=NOW,
        resolve_verification_key=_resolve_key,
        trust_root=_trust_root,
        resolve_revocation=_always_active,
    )
    assert result.state == VALID
    assert RECORDS["new_root"]["issuer"] != RECORDS["old_root"]["issuer"]
    assert RECORDS["new_leaf_agent_x"]["subject"] == RECORDS["old_leaf_agent_x"]["subject"]


# 6. a descendant only on the old branch, with no replacement in the fixture


def test_old_branch_descendant_with_no_replacement_stays_invalid() -> None:
    assert "new_leaf_agent_y" not in RECORDS
    old_chain_y = [RECORDS["old_root"], RECORDS["old_leaf_agent_y"]]
    result = verify_delegation_authority(
        old_chain_y,
        expected_delegation_ref=META["old_leaf_agent_y_delegation_ref"],
        now=NOW,
        resolve_verification_key=_resolve_key,
        trust_root=_trust_root,
        resolve_revocation=_revoked_only(RECORDS["old_root"]["delegation_id"]),
    )
    assert result.state == INVALID
    assert result.failures[0].code == "REVOKED"
    assert result.failures[0].index == 0


# 7. no union: one call verifies exactly one chain


def test_old_and_new_presented_together_do_not_combine_into_valid_authority() -> None:
    concatenated = [
        RECORDS["old_root"],
        RECORDS["old_leaf_agent_x"],
        RECORDS["new_root"],
        RECORDS["new_leaf_agent_x"],
    ]
    result = verify_delegation_authority(
        concatenated,
        expected_delegation_ref=META["new_leaf_agent_x_delegation_ref"],
        now=NOW,
        resolve_verification_key=_resolve_key,
        trust_root=_trust_root,
        resolve_revocation=_always_active,
    )
    assert result.state != VALID
    assert result.state == INVALID
    assert result.failures[0].code == "PARENT_MISMATCH"
    assert result.failures[0].index == 2


def test_verify_delegation_authority_takes_exactly_one_chain_argument() -> None:
    import inspect

    parameters = inspect.signature(verify_delegation_authority).parameters
    assert list(parameters)[0] == "chain"
    assert parameters["chain"].kind in (
        inspect.Parameter.POSITIONAL_ONLY,
        inspect.Parameter.POSITIONAL_OR_KEYWORD,
    )
    # No second chain-shaped parameter exists to merge scopes or budgets across.
    assert "other_chain" not in parameters
    assert "chains" not in parameters
