"""APS action receipt as external action evidence: verifier tests.

Two sources of receipts:

- the committed fixture in ``fixtures/action-receipt/``, regenerated byte for
  byte by ``generate.py`` from published seeds, verified at the fixed
  ``reference_time`` in ``meta.json`` so the result is the same on every run.
- receipts minted in-process with ephemeral keys for the mutation cases.

Every negative case mutates exactly one thing and asserts both the status and
the check that carried it, so a refusal is attributed rather than assumed.
"""
from __future__ import annotations

import copy
import hashlib
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest
from agent_passport import compute_action_ref
from agent_passport.crypto import generate_key_pair
from agent_passport.receipt_core import create_receipt_v1

from aps_action_receipt import (
    ACTION_INTENT_RECEIPT_TYPE,
    CHECKS,
    FAIL,
    INVALID,
    NOT_CHECKED,
    PASS,
    STATUSES,
    UNVERIFIED,
    VERIFIED,
    verify_aps_action_receipt,
)

FIXTURE_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "action-receipt"
FIXTURE_RECEIPT_SHA256 = "2727fb6eda3db229613951e7b61949c848ecb4cf632e1c6d163b8f22f4270235"

ISSUER = "did:aps:test:gateway"
KEY_ID = "k1"
AGENT = "did:aps:test:agent"
DELEGATION_REF = hashlib.sha256(b"test-delegation").hexdigest()
ISSUED_AT = datetime(2026, 9, 18, 12, 0, 0, tzinfo=timezone.utc)
REFERENCE = ISSUED_AT + timedelta(minutes=5)
MAX_AGE = 600


def _iso_ms(value: datetime) -> str:
    return value.strftime("%Y-%m-%dT%H:%M:%S.") + f"{value.microsecond // 1000:03d}Z"


def _action(agent: str = AGENT) -> dict:
    return {
        "agent_id": agent,
        "action_type": "calendar.event.create",
        "scope_required": ["calendar:write"],
        "timestamp": "2026-09-18T11:59:58Z",
    }


def _mint(
    *,
    issued_at: datetime = ISSUED_AT,
    action: dict | None = None,
    receipt_type: str = ACTION_INTENT_RECEIPT_TYPE,
    subject_agent: str = AGENT,
) -> tuple[dict, dict, dict]:
    """Return (receipt, pinned keys, action preimage) with an ephemeral issuer key."""
    action = action or _action()
    keys = generate_key_pair()
    fields = {
        "profile": "aps-receipt-v1",
        "receipt_type": receipt_type,
        "issuer": ISSUER,
        "subject_agent": subject_agent,
        "action_ref": compute_action_ref(**action),
        "delegation_ref": DELEGATION_REF,
        "issued_at": _iso_ms(issued_at),
        "evidence_refs": [],
        "result": {"intent_id": "itn-1"},
    }
    receipt = create_receipt_v1(fields, [{"signer": ISSUER, "key_id": KEY_ID, "private_key": keys["privateKey"]}])
    return receipt, {ISSUER: {KEY_ID: keys["publicKey"]}}, action


def _resolver(pinned: dict):
    return lambda signer, key_id, _issued_at: pinned.get(signer, {}).get(key_id)


def _verify(receipt: dict, pinned: dict, action: dict | None, **overrides) -> dict:
    kwargs = dict(
        resolve_key=_resolver(pinned),
        reference_time=REFERENCE,
        max_age_seconds=MAX_AGE,
        expected_subject_agent=AGENT,
        expected_delegation_ref=DELEGATION_REF,
        action=action,
    )
    kwargs.update(overrides)
    return verify_aps_action_receipt(receipt, **kwargs)


# Committed fixture


def test_fixture_is_the_committed_bytes() -> None:
    digest = hashlib.sha256((FIXTURE_DIR / "receipt.json").read_bytes()).hexdigest()
    assert digest == FIXTURE_RECEIPT_SHA256


def test_committed_fixture_verifies_at_its_reference_time() -> None:
    receipt = json.loads((FIXTURE_DIR / "receipt.json").read_text())
    action = json.loads((FIXTURE_DIR / "action.json").read_text())
    keys = json.loads((FIXTURE_DIR / "keys.json").read_text())
    meta = json.loads((FIXTURE_DIR / "meta.json").read_text())
    result = verify_aps_action_receipt(
        receipt,
        resolve_key=_resolver(keys["pinned"]),
        reference_time=datetime.fromisoformat(meta["reference_time"].replace("Z", "+00:00")),
        max_age_seconds=meta["max_age_seconds"],
        expected_subject_agent=meta["expected_subject_agent"],
        expected_delegation_ref=meta["expected_delegation_ref"],
        action=action,
    )
    assert result["status"] == VERIFIED
    assert all(result["checks"][name] == PASS for name in CHECKS)
    assert result["reasons"] == []
    assert result["receipt_type"] == ACTION_INTENT_RECEIPT_TYPE
    assert result["checks"]["receipt_type"] == PASS


def test_committed_fixture_is_stale_one_day_later() -> None:
    receipt = json.loads((FIXTURE_DIR / "receipt.json").read_text())
    keys = json.loads((FIXTURE_DIR / "keys.json").read_text())
    meta = json.loads((FIXTURE_DIR / "meta.json").read_text())
    later = datetime.fromisoformat(meta["reference_time"].replace("Z", "+00:00")) + timedelta(days=1)
    result = verify_aps_action_receipt(
        receipt, resolve_key=_resolver(keys["pinned"]), reference_time=later, max_age_seconds=meta["max_age_seconds"]
    )
    assert result["status"] == INVALID
    assert result["checks"]["freshness"] == FAIL
    assert result["checks"]["signature"] == PASS
    assert result["reasons"] == ["stale"]


# Positive path, ephemeral key


def test_valid_receipt_passes_every_check() -> None:
    receipt, pinned, action = _mint()
    result = _verify(receipt, pinned, action)
    assert result["status"] == VERIFIED
    assert set(result["checks"]) == set(CHECKS)
    assert all(state == PASS for state in result["checks"].values())


def test_omitted_expectations_are_reported_not_checked_and_still_valid() -> None:
    receipt, pinned, _ = _mint()
    result = _verify(receipt, pinned, None, expected_subject_agent=None, expected_delegation_ref=None)
    assert result["status"] == VERIFIED
    assert result["checks"]["subject_agent"] == NOT_CHECKED
    assert result["checks"]["delegation_ref"] == NOT_CHECKED
    assert result["checks"]["action_binding"] == NOT_CHECKED


# Negative cases, one mutation each


def test_corrupt_signature_is_invalid() -> None:
    receipt, pinned, action = _mint()
    mutated = copy.deepcopy(receipt)
    value = mutated["signatures"][0]["value"]
    mutated["signatures"][0]["value"] = ("0" if value[0] != "0" else "1") + value[1:]
    result = _verify(mutated, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["signature"] == FAIL
    assert result["checks"]["receipt_id"] == PASS  # the id excludes signatures


def test_tampered_field_breaks_receipt_id_and_signature() -> None:
    receipt, pinned, action = _mint()
    mutated = copy.deepcopy(receipt)
    mutated["result"] = {"intent_id": "itn-2"}
    result = _verify(mutated, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["receipt_id"] == FAIL
    assert result["checks"]["signature"] == FAIL


def test_unpinned_issuer_key_is_unverified_not_invalid() -> None:
    receipt, _, action = _mint()
    result = _verify(receipt, {}, action)
    assert result["status"] == UNVERIFIED
    assert result["checks"]["signature"] == NOT_CHECKED
    assert result["reasons"] == [f"signature:{ISSUER}:{KEY_ID}:key_unresolved"]
    # Everything that could be checked still was.
    for name in ("structure", "receipt_id", "receipt_type", "subject_agent", "delegation_ref", "action_binding", "freshness"):
        assert result["checks"][name] == PASS


def test_wrong_pinned_key_is_invalid() -> None:
    receipt, _, action = _mint()
    wrong = {ISSUER: {KEY_ID: generate_key_pair()["publicKey"]}}
    result = _verify(receipt, wrong, action)
    assert result["status"] == INVALID
    assert result["checks"]["signature"] == FAIL


def test_resolver_error_is_unverified() -> None:
    receipt, _, action = _mint()

    def broken(_signer, _key_id, _issued_at):
        raise RuntimeError("key store unreachable")

    result = _verify(receipt, {}, action, resolve_key=broken)
    assert result["status"] == UNVERIFIED
    assert result["reasons"] == [f"signature:{ISSUER}:{KEY_ID}:key_resolution_error"]


def test_wrong_agent_expectation_is_invalid() -> None:
    receipt, pinned, action = _mint()
    result = _verify(receipt, pinned, action, expected_subject_agent="did:aps:test:someone-else")
    assert result["status"] == INVALID
    assert result["checks"]["subject_agent"] == FAIL
    assert "subject_agent_mismatch" in result["reasons"]


def test_wrong_delegation_expectation_is_invalid() -> None:
    receipt, pinned, action = _mint()
    result = _verify(receipt, pinned, action, expected_delegation_ref="f" * 64)
    assert result["status"] == INVALID
    assert result["checks"]["delegation_ref"] == FAIL


def test_different_action_preimage_is_invalid() -> None:
    receipt, pinned, action = _mint()
    other = dict(action, action_type="calendar.event.delete")
    result = _verify(receipt, pinned, other)
    assert result["status"] == INVALID
    assert result["checks"]["action_binding"] == FAIL
    assert "action_ref_mismatch" in result["reasons"]


def test_action_preimage_without_canonical_form_is_invalid() -> None:
    receipt, pinned, action = _mint()
    duplicated = dict(action, scope_required=["calendar:write", "calendar:write"])
    result = _verify(receipt, pinned, duplicated)
    assert result["status"] == INVALID
    assert result["checks"]["action_binding"] == FAIL
    assert "action_preimage_has_no_canonical_form" in result["reasons"]


def test_other_receipt_type_is_invalid_even_when_correctly_signed() -> None:
    receipt, pinned, action = _mint(receipt_type="aps:policy-decision:v1")
    result = _verify(receipt, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["receipt_type"] == FAIL
    assert result["checks"]["signature"] == PASS
    assert result["reasons"] == ["receipt_type_mismatch"]
    accepted = _verify(receipt, pinned, action, expected_receipt_type="aps:policy-decision:v1")
    assert accepted["checks"]["receipt_type"] == PASS


def test_preimage_agent_must_match_subject_agent_without_a_caller_expectation() -> None:
    # The signed receipt says agent B, the action digest was computed for agent A.
    # The digest matches, because the receipt was minted over that preimage, and
    # the caller supplied no expected_subject_agent. The binding check still fails.
    other_agent = "did:aps:test:other-agent"
    receipt, pinned, action = _mint(subject_agent=other_agent)
    result = _verify(receipt, pinned, action, expected_subject_agent=None)
    assert result["status"] == INVALID
    assert result["checks"]["subject_agent"] == NOT_CHECKED
    assert result["checks"]["action_binding"] == FAIL
    assert result["reasons"] == ["action_agent_mismatch"]


def test_stale_receipt_is_invalid() -> None:
    receipt, pinned, action = _mint()
    result = _verify(receipt, pinned, action, reference_time=ISSUED_AT + timedelta(seconds=MAX_AGE + 1))
    assert result["status"] == INVALID
    assert result["checks"]["freshness"] == FAIL
    assert result["reasons"] == ["stale"]


def test_receipt_from_the_future_is_invalid_without_skew() -> None:
    receipt, pinned, action = _mint(issued_at=REFERENCE + timedelta(seconds=30))
    result = _verify(receipt, pinned, action)
    assert result["status"] == INVALID
    assert result["reasons"] == ["issued_in_future"]
    tolerated = _verify(receipt, pinned, action, clock_skew_seconds=60)
    assert tolerated["status"] == VERIFIED


def test_malformed_receipt_is_invalid_and_stops_at_structure() -> None:
    receipt, pinned, action = _mint()
    mutated = copy.deepcopy(receipt)
    del mutated["action_ref"]
    result = _verify(mutated, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["structure"] == FAIL
    assert result["receipt_type"] is None
    for name in CHECKS[1:]:
        assert result["checks"][name] == NOT_CHECKED


def test_reference_time_must_be_aware() -> None:
    receipt, pinned, action = _mint()
    with pytest.raises(ValueError):
        _verify(receipt, pinned, action, reference_time=datetime(2026, 9, 18, 12, 5))


def test_status_vocabulary_is_closed() -> None:
    assert set(STATUSES) == {VERIFIED, INVALID, UNVERIFIED}
