"""APS action intent receipt as external action evidence: verifier tests.

Two sources of receipts:

- the committed fixture in ``fixtures/action-receipt/``, regenerated byte for
  byte by ``generate.py`` from published seeds, verified at the fixed
  ``reference_time`` in ``meta.json`` so the result is the same on every run.
- receipts minted in-process with ephemeral keys for the negative cases.

Every negative case changes exactly one thing and asserts both the status and
the check that carried it, so a refusal is attributed rather than assumed.

Stage negatives are minted, never mutated. ``create_receipt_v1`` deliberately
does not enforce the draft section 5.3 rules, so a stage-invalid record can be
built with a correct ``receipt_id`` and a valid signature. Mutating a signed
receipt instead would break the identifier and the signature as well, and the
test would no longer isolate the stage rule it claims to cover.
"""
from __future__ import annotations

import copy
import hashlib
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest
from agent_passport import (
    compute_action_ref,
    compute_action_ref_v2,
    compute_payload_ref_v1,
    create_action_reference_input_v2,
    verify_authority_delegation_chain,
)
from agent_passport.crypto import generate_key_pair
from agent_passport.receipt_core import create_receipt_v1

from aps_action_receipt import (
    ACTION_INTENT_RECEIPT_TYPE,
    CHECKS,
    FAIL,
    INVALID,
    NOT_CHECKED,
    PASS,
    STATUSES,
    UNVERIFIED,
    VERIFIED,
    verify_aps_action_receipt,
)

FIXTURE_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "action-receipt"
FIXTURE_RECEIPT_SHA256 = "cbbea5a88ff06729f8bfeac0a6878b1a640231709ce3846eae58f5af435dcd60"

AGENT = "did:aps:test:agent"
KEY_ID = "k1"
#: An AuthorityDelegationV1 identifier, which carries its own ``sha256:``
#: prefix. A bare digest here is refused by the envelope validator, which one
#: of the regression tests below pins.
DELEGATION_REF = "sha256:" + hashlib.sha256(b"test-delegation").hexdigest()
ISSUED_AT = datetime(2026, 9, 18, 12, 0, 0, tzinfo=timezone.utc)
REFERENCE = ISSUED_AT + timedelta(minutes=5)
MAX_AGE = 600
INTENT_RESULT = {"profile": "aps-action-intent-result-v1", "status": "declared"}


def _iso_ms(value: datetime) -> str:
    return value.strftime("%Y-%m-%dT%H:%M:%S.") + f"{value.microsecond // 1000:03d}Z"


def _action(agent: str = AGENT, **overrides) -> dict:
    """The exact aps-action-ref-v2 input object, built by the SDK."""
    fields = {
        "agent_id": agent,
        "action_type": "calendar.event.create",
        "target": "https://calendar.example.com/calendars/primary",
        "payload_ref": compute_payload_ref_v1({"title": "test"}),
        "scope_required": ["calendar:write"],
        "issued_at": "2026-09-18T11:59:58.000Z",
        "nonce": "0" * 32,
    }
    fields.update(overrides)
    return create_action_reference_input_v2(**fields)


def _mint(
    *,
    issued_at: datetime = ISSUED_AT,
    action: dict | None = None,
    receipt_type: str = ACTION_INTENT_RECEIPT_TYPE,
    subject_agent: str = AGENT,
    issuer: str | None = None,
    action_ref: str | None = None,
    result: dict | None = None,
    delegation_ref: str = DELEGATION_REF,
    extra: dict | None = None,
) -> tuple[dict, dict, dict]:
    """Return (receipt, pinned keys, action preimage) with an ephemeral issuer key.

    Defaults mint a draft section 5.3.1 conformant action intent: the issuer is
    the acting agent and signs, and the result is the exact declaration object.
    Every argument exists so a single one of those properties can be broken
    while the envelope, the identifier and the signature stay correct.
    """
    action = _action() if action is None else action
    issuer = subject_agent if issuer is None else issuer
    keys = generate_key_pair()
    fields = {
        "profile": "aps-receipt-v1",
        "receipt_type": receipt_type,
        "issuer": issuer,
        "subject_agent": subject_agent,
        "action_ref": compute_action_ref_v2(action) if action_ref is None else action_ref,
        "delegation_ref": delegation_ref,
        "issued_at": _iso_ms(issued_at),
        "evidence_refs": [],
        "result": INTENT_RESULT if result is None else result,
    }
    fields.update(extra or {})
    receipt = create_receipt_v1(
        fields, [{"signer": issuer, "key_id": KEY_ID, "private_key": keys["privateKey"]}]
    )
    return receipt, {issuer: {KEY_ID: keys["publicKey"]}}, action


def _resolver(pinned: dict):
    return lambda signer, key_id, _issued_at: pinned.get(signer, {}).get(key_id)


def _verify(receipt: dict, pinned: dict, action: dict | None, **overrides) -> dict:
    kwargs = dict(
        resolve_key=_resolver(pinned),
        reference_time=REFERENCE,
        max_age_seconds=MAX_AGE,
        expected_subject_agent=AGENT,
        expected_delegation_ref=DELEGATION_REF,
        action=action,
    )
    kwargs.update(overrides)
    return verify_aps_action_receipt(receipt, **kwargs)


def _fixture(name: str) -> dict:
    return json.loads((FIXTURE_DIR / name).read_text())


# Committed fixture


def test_fixture_is_the_committed_bytes() -> None:
    digest = hashlib.sha256((FIXTURE_DIR / "receipt.json").read_bytes()).hexdigest()
    assert digest == FIXTURE_RECEIPT_SHA256


def test_committed_fixture_verifies_at_its_reference_time() -> None:
    meta = _fixture("meta.json")
    result = verify_aps_action_receipt(
        _fixture("receipt.json"),
        resolve_key=_resolver(_fixture("keys.json")["pinned"]),
        reference_time=datetime.fromisoformat(meta["reference_time"].replace("Z", "+00:00")),
        max_age_seconds=meta["max_age_seconds"],
        expected_subject_agent=meta["expected_subject_agent"],
        expected_delegation_ref=meta["expected_delegation_ref"],
        action=_fixture("action.json"),
    )
    assert result["status"] == VERIFIED
    assert all(result["checks"][name] == PASS for name in CHECKS)
    assert result["reasons"] == []
    assert result["receipt_type"] == ACTION_INTENT_RECEIPT_TYPE
    assert result["core_status"] == "valid"
    assert result["other_signatures"] == "none"


def test_committed_fixture_is_stale_one_day_later() -> None:
    meta = _fixture("meta.json")
    later = datetime.fromisoformat(meta["reference_time"].replace("Z", "+00:00")) + timedelta(days=1)
    result = verify_aps_action_receipt(
        _fixture("receipt.json"),
        resolve_key=_resolver(_fixture("keys.json")["pinned"]),
        reference_time=later,
        max_age_seconds=meta["max_age_seconds"],
    )
    assert result["status"] == INVALID
    assert result["checks"]["freshness"] == FAIL
    assert result["checks"]["signature"] == PASS
    assert result["reasons"] == ["stale"]


# Identifier forms. Both inverse mistakes have been made in this project, in
# different sessions, so each direction is pinned rather than described.


def test_payload_ref_is_the_domain_separated_construction() -> None:
    action = _fixture("action.json")
    assert action["payload_ref"] == compute_payload_ref_v1(_fixture("payload.json"))
    # Not a bare digest over the payload bytes. That value is the right shape
    # and the wrong number, so only this comparison catches the difference.
    naive = hashlib.sha256(
        json.dumps(_fixture("payload.json"), sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    assert action["payload_ref"] != naive


def test_action_ref_is_the_v2_construction_over_the_committed_input() -> None:
    assert compute_action_ref_v2(_fixture("action.json")) == _fixture("receipt.json")["action_ref"]


def test_legacy_action_ref_digest_cannot_satisfy_the_v2_binding() -> None:
    # compute_action_ref is a pre-draft compatibility digest over a different,
    # camelCase preimage. It is deliberately still shipped. It is not an
    # action_ref and must never bind one.
    action = _action()
    legacy = compute_action_ref(
        agent_id=action["agent_id"],
        action_type=action["action_type"],
        scope_required=action["scope_required"],
        timestamp=action["issued_at"],
    )
    assert legacy != compute_action_ref_v2(action)
    # Minted carrying the legacy digest from the start, not mutated afterwards,
    # so the identifier and the signature stay correct and the binding is the
    # only thing that fails.
    receipt, pinned, _ = _mint(action=action, action_ref=legacy)
    result = _verify(receipt, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["receipt_id"] == PASS
    assert result["checks"]["signature"] == PASS
    assert result["checks"]["stage"] == PASS
    assert result["checks"]["action_binding"] == FAIL
    assert result["reasons"] == ["action_ref_mismatch"]


def test_delegation_ref_without_the_sha256_prefix_is_refused() -> None:
    receipt, pinned, action = _mint()
    bare = copy.deepcopy(receipt)
    bare["delegation_ref"] = receipt["delegation_ref"].removeprefix("sha256:")
    result = _verify(bare, pinned, action, expected_delegation_ref=bare["delegation_ref"])
    assert result["status"] == INVALID
    assert result["checks"]["structure"] == FAIL
    assert result["reasons"] == ["ReceiptV1: delegation_ref"]


def test_action_ref_with_a_sha256_prefix_is_refused() -> None:
    receipt, pinned, action = _mint()
    prefixed = copy.deepcopy(receipt)
    prefixed["action_ref"] = "sha256:" + receipt["action_ref"]
    result = _verify(prefixed, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["structure"] == FAIL
    assert result["reasons"] == ["ReceiptV1: action_ref"]


def test_committed_delegation_id_is_what_the_receipt_and_meta_reference() -> None:
    delegation = _fixture("delegation.json")
    assert _fixture("receipt.json")["delegation_ref"] == delegation["delegation_id"]
    assert _fixture("meta.json")["expected_delegation_ref"] == delegation["delegation_id"]


def test_committed_delegation_verifies_on_its_own_and_the_receipt_does_not_establish_it() -> None:
    delegation = _fixture("delegation.json")
    keys = _fixture("keys.json")["delegation_verification_key"]
    chain = verify_authority_delegation_chain(
        [delegation],
        now="2026-09-18T12:00:00.000Z",
        resolve_verification_key=lambda *_args: keys[delegation["verification_method"]],
        trust_root=lambda _root: True,
        resolve_revocation=lambda _delegation: "active",
    )
    assert chain.state == "valid"
    # That result came from verify_authority_delegation_chain, not from the
    # receipt verifier. The receipt verifier only compares delegation_ref to
    # the caller's expectation, so it reports delegation_ref as checked while
    # establishing nothing about the delegation itself.
    meta = _fixture("meta.json")
    result = verify_aps_action_receipt(
        _fixture("receipt.json"),
        resolve_key=_resolver(_fixture("keys.json")["pinned"]),
        reference_time=datetime.fromisoformat(meta["reference_time"].replace("Z", "+00:00")),
        max_age_seconds=meta["max_age_seconds"],
        expected_delegation_ref=delegation["delegation_id"],
    )
    assert result["checks"]["delegation_ref"] == PASS
    assert result["reasons"] == []


def test_the_delegation_check_is_string_equality_and_nothing_more() -> None:
    # The boundary made visible: a receipt naming a delegation that does not
    # exist anywhere still passes the delegation_ref check, because the check
    # is a comparison against what the caller said to expect. Establishing that
    # the delegation is real, current and unrevoked is
    # verify_authority_delegation_chain's job and happens elsewhere.
    invented = "sha256:" + "9" * 64
    receipt, pinned, action = _mint(delegation_ref=invented)
    result = _verify(receipt, pinned, action, expected_delegation_ref=invented)
    assert result["status"] == VERIFIED
    assert result["checks"]["delegation_ref"] == PASS


# Section 5.3.1 stage rules, one minted record per failure code


def test_intent_issued_by_someone_other_than_the_acting_agent_fails_the_stage() -> None:
    receipt, pinned, action = _mint(issuer="did:aps:test:gateway")
    result = _verify(receipt, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["stage"] == FAIL
    assert "INTENT_ISSUER_NOT_ACTING_AGENT" in result["reasons"]
    # The envelope, the identifier and the signature are all intact. Only the
    # stage rule failed, which is the point of minting rather than mutating.
    assert result["checks"]["structure"] == PASS
    assert result["checks"]["receipt_id"] == PASS
    assert result["checks"]["signature"] == PASS
    assert result["checks"]["receipt_type"] == PASS


def test_intent_carrying_prev_fails_the_stage() -> None:
    receipt, pinned, action = _mint(extra={"prev": "a" * 64})
    result = _verify(receipt, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["stage"] == FAIL
    assert "INTENT_PREV_PRESENT" in result["reasons"]
    assert result["checks"]["receipt_id"] == PASS


def test_intent_carrying_decision_ref_fails_the_stage() -> None:
    receipt, pinned, action = _mint(extra={"decision_ref": "b" * 64})
    result = _verify(receipt, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["stage"] == FAIL
    assert "INTENT_DECISION_REF_PRESENT" in result["reasons"]


def test_intent_result_under_another_profile_fails_the_stage() -> None:
    receipt, pinned, action = _mint(result={"profile": "vendor-result-v1", "status": "declared"})
    result = _verify(receipt, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["stage"] == FAIL
    assert "INTENT_RESULT_PROFILE" in result["reasons"]


def test_intent_result_that_is_not_exactly_declared_fails_the_stage() -> None:
    receipt, pinned, action = _mint(
        result={"profile": "aps-action-intent-result-v1", "status": "executed"}
    )
    result = _verify(receipt, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["stage"] == FAIL
    assert "INTENT_RESULT_INVALID" in result["reasons"]


def test_another_receipt_type_is_the_wrong_artifact_class_not_a_stage_failure() -> None:
    receipt, pinned, action = _mint(receipt_type="aps:policy-decision:v1")
    result = _verify(receipt, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["receipt_type"] == FAIL
    # The stage rules of a type this verifier does not accept were never the
    # question, so the stage axis reports not_checked rather than a failure.
    assert result["checks"]["stage"] == NOT_CHECKED
    assert result["checks"]["signature"] == PASS
    assert result["reasons"] == ["receipt_type_mismatch"]


def test_a_foreign_envelope_profile_is_not_judged_against_this_schema() -> None:
    receipt, pinned, action = _mint()
    foreign = copy.deepcopy(receipt)
    foreign["profile"] = "vendor-receipt-v1"
    result = _verify(foreign, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["structure"] == FAIL
    assert result["core_status"] == "unsupported"
    assert result["reasons"] == ["unsupported_profile"]
    assert result["receipt_type"] is None


# Key resolution. Every outcome where no signature was checked is a non
# verification. Only a checked signature that did not verify is a failure.


@pytest.mark.parametrize(
    "resolved,reason",
    [
        (None, "key_unresolved"),
        ({"outcome": "not_found"}, "key_not_found"),
        ({"outcome": "ambiguous"}, "key_ambiguous"),
        ({"outcome": "malformed"}, "key_material_malformed"),
        ({"outcome": "unreachable"}, "key_unreachable"),
        ("zz", "key_material_malformed"),
    ],
)
def test_resolution_outcomes_are_unverified_and_never_a_failed_signature(resolved, reason) -> None:
    receipt, _pinned, action = _mint()
    result = _verify(receipt, {}, action, resolve_key=lambda *_args: resolved)
    assert result["status"] == UNVERIFIED
    assert result["checks"]["signature"] == NOT_CHECKED
    assert result["reasons"] == [f"signature:{AGENT}:{KEY_ID}:{reason}"]


def test_unsupported_key_scheme_is_unverified_and_keeps_the_core_status() -> None:
    # The one place an APS `unsupported` state translates to a TRACE side
    # non verification. The scheme was not verified and is not pretended to be.
    receipt, _pinned, action = _mint()
    result = _verify(receipt, {}, action, resolve_key=lambda *_a: {"outcome": "unsupported_scheme"})
    assert result["status"] == UNVERIFIED
    assert result["core_status"] == "unsupported"
    assert result["checks"]["signature"] == NOT_CHECKED
    assert result["reasons"] == [f"signature:{AGENT}:{KEY_ID}:key_scheme_unsupported"]


def test_resolver_error_is_unverified() -> None:
    receipt, _pinned, action = _mint()

    def broken(_signer, _key_id, _issued_at):
        raise RuntimeError("key store unreachable")

    result = _verify(receipt, {}, action, resolve_key=broken)
    assert result["status"] == UNVERIFIED
    assert result["reasons"] == [f"signature:{AGENT}:{KEY_ID}:key_resolution_error"]


def test_wrong_pinned_key_is_the_only_failed_signature_case() -> None:
    receipt, _pinned, action = _mint()
    wrong = {AGENT: {KEY_ID: generate_key_pair()["publicKey"]}}
    result = _verify(receipt, wrong, action)
    assert result["status"] == INVALID
    assert result["checks"]["signature"] == FAIL
    assert result["reasons"] == [f"signature:{AGENT}:{KEY_ID}:invalid"]


def test_an_appended_non_required_signature_cannot_move_the_result() -> None:
    # Signatures sit outside the receipt_id preimage, so a third party can
    # append a descriptor to a published receipt without changing its
    # identifier. Letting that put a failure reason on a verified result would
    # hand this module's output to that third party.
    receipt, pinned, action = _mint()
    appended = copy.deepcopy(receipt)
    appended["signatures"].append(
        {"alg": "Ed25519", "key_id": "zz", "signer": "did:aps:test:zz-observer", "value": "ab" * 64}
    )
    result = _verify(appended, pinned, action)
    assert result["status"] == VERIFIED
    assert result["checks"]["signature"] == PASS
    assert result["reasons"] == []
    assert result["other_signatures"] == "not_all_verified"
    assert result["checks"]["receipt_id"] == PASS


# Precedence and the translation guard


def test_invalid_wins_over_unverified_when_both_apply() -> None:
    # An unresolved required signer alone is unverified. A wrapper side failure
    # alongside it makes the result invalid, and both reasons stay visible.
    receipt, _pinned, action = _mint()
    result = _verify(
        receipt,
        {},
        action,
        reference_time=ISSUED_AT + timedelta(seconds=MAX_AGE + 1),
    )
    assert result["status"] == INVALID
    assert result["checks"]["signature"] == NOT_CHECKED
    assert result["checks"]["freshness"] == FAIL
    assert f"signature:{AGENT}:{KEY_ID}:key_unresolved" in result["reasons"]
    assert "stale" in result["reasons"]


def test_an_unmapped_core_invalid_state_cannot_read_as_verified(monkeypatch) -> None:
    # Synthetic. Unreachable through this wrapper on 4.0.0, where every invalid
    # state the SDK reports arrives on an axis the translation maps. It exists
    # so a future SDK state cannot silently pass, and it is the one case where
    # no entry in `checks` carries the result.
    receipt, pinned, action = _mint()
    import aps_action_receipt as module

    real = module.verify_receipt_v1

    def unmapped(*args, **kwargs):
        core = dict(real(*args, **kwargs))
        core["status"] = "invalid"
        core["errors"] = ["some_future_code"]
        return core

    monkeypatch.setattr(module, "verify_receipt_v1", unmapped)
    result = _verify(receipt, pinned, action)
    assert result["status"] == INVALID
    assert not any(state == FAIL for state in result["checks"].values())
    assert result["reasons"] == ["unmapped_core_invalid:some_future_code"]


# Caller expectations, action binding and freshness


def test_valid_receipt_passes_every_check() -> None:
    receipt, pinned, action = _mint()
    result = _verify(receipt, pinned, action)
    assert result["status"] == VERIFIED
    assert set(result["checks"]) == set(CHECKS)
    assert all(state == PASS for state in result["checks"].values())


def test_omitted_expectations_are_reported_not_checked_and_still_valid() -> None:
    receipt, pinned, _ = _mint()
    result = _verify(receipt, pinned, None, expected_subject_agent=None, expected_delegation_ref=None)
    assert result["status"] == VERIFIED
    assert result["checks"]["subject_agent"] == NOT_CHECKED
    assert result["checks"]["delegation_ref"] == NOT_CHECKED
    assert result["checks"]["action_binding"] == NOT_CHECKED


def test_wrong_agent_expectation_is_invalid() -> None:
    receipt, pinned, action = _mint()
    result = _verify(receipt, pinned, action, expected_subject_agent="did:aps:test:someone-else")
    assert result["status"] == INVALID
    assert result["checks"]["subject_agent"] == FAIL
    assert "subject_agent_mismatch" in result["reasons"]


def test_wrong_delegation_expectation_is_invalid() -> None:
    receipt, pinned, action = _mint()
    result = _verify(receipt, pinned, action, expected_delegation_ref="sha256:" + "f" * 64)
    assert result["status"] == INVALID
    assert result["checks"]["delegation_ref"] == FAIL


def test_different_action_preimage_is_invalid() -> None:
    receipt, pinned, action = _mint()
    other = _action(action_type="calendar.event.delete")
    result = _verify(receipt, pinned, other)
    assert result["status"] == INVALID
    assert result["checks"]["action_binding"] == FAIL
    assert "action_ref_mismatch" in result["reasons"]


def test_action_preimage_without_canonical_form_is_invalid() -> None:
    receipt, pinned, action = _mint()
    duplicated = dict(action, scope_required=["calendar:write", "calendar:write"])
    result = _verify(receipt, pinned, duplicated)
    assert result["status"] == INVALID
    assert result["checks"]["action_binding"] == FAIL
    assert result["reasons"] == ["action_preimage_invalid:scope_not_canonical"]


def test_preimage_agent_must_match_subject_agent_without_a_caller_expectation() -> None:
    # The receipt is minted over the default preimage, whose agent_id is AGENT,
    # while its subject_agent says other_agent. Verifying against that same
    # preimage means the digest matches and the caller supplied no
    # expected_subject_agent, so the agent comparison is the only thing left
    # that can fail.
    other_agent = "did:aps:test:other-agent"
    receipt, pinned, action = _mint(subject_agent=other_agent)
    assert compute_action_ref_v2(action) == receipt["action_ref"]
    result = _verify(receipt, pinned, action, expected_subject_agent=None)
    assert result["status"] == INVALID
    assert result["checks"]["subject_agent"] == NOT_CHECKED
    assert result["checks"]["action_binding"] == FAIL
    assert result["reasons"] == ["action_agent_mismatch"]


def test_stale_receipt_is_invalid() -> None:
    receipt, pinned, action = _mint()
    result = _verify(receipt, pinned, action, reference_time=ISSUED_AT + timedelta(seconds=MAX_AGE + 1))
    assert result["status"] == INVALID
    assert result["checks"]["freshness"] == FAIL
    assert result["reasons"] == ["stale"]


def test_receipt_from_the_future_is_invalid_without_skew() -> None:
    receipt, pinned, action = _mint(issued_at=REFERENCE + timedelta(seconds=30))
    result = _verify(receipt, pinned, action)
    assert result["status"] == INVALID
    assert result["reasons"] == ["issued_in_future"]
    tolerated = _verify(receipt, pinned, action, clock_skew_seconds=60)
    assert tolerated["status"] == VERIFIED


def test_corrupt_signature_is_invalid_and_the_id_still_verifies() -> None:
    receipt, pinned, action = _mint()
    mutated = copy.deepcopy(receipt)
    value = mutated["signatures"][0]["value"]
    mutated["signatures"][0]["value"] = ("0" if value[0] != "0" else "1") + value[1:]
    result = _verify(mutated, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["signature"] == FAIL
    assert result["checks"]["receipt_id"] == PASS  # the id excludes signatures


def test_tampered_field_breaks_receipt_id_and_signature() -> None:
    receipt, pinned, action = _mint()
    mutated = copy.deepcopy(receipt)
    mutated["issued_at"] = _iso_ms(ISSUED_AT + timedelta(seconds=1))
    result = _verify(mutated, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["receipt_id"] == FAIL
    assert result["checks"]["signature"] == FAIL


def test_malformed_receipt_is_invalid_and_stops_at_structure() -> None:
    receipt, pinned, action = _mint()
    mutated = copy.deepcopy(receipt)
    del mutated["action_ref"]
    result = _verify(mutated, pinned, action)
    assert result["status"] == INVALID
    assert result["checks"]["structure"] == FAIL
    assert result["receipt_type"] is None
    for name in CHECKS[1:]:
        assert result["checks"][name] == NOT_CHECKED


def test_reference_time_must_be_aware() -> None:
    receipt, pinned, action = _mint()
    with pytest.raises(ValueError):
        _verify(receipt, pinned, action, reference_time=datetime(2026, 9, 18, 12, 5))


def test_status_vocabulary_is_closed() -> None:
    assert set(STATUSES) == {VERIFIED, INVALID, UNVERIFIED}
