"""Offline validation of the pinned UCP checkout shapes, not purchase authorization.

The JSON Schemas are generated by the released upstream annotation resolver.
Validate the original object before the SDK can coerce any values, then exercise
the official released SDK model too. Neither result authenticates a merchant,
authorizes a payment, or establishes negotiation of an extension capability.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator, FormatChecker
from jsonschema.exceptions import ValidationError as JsonSchemaValidationError
from pydantic import ValidationError as ModelValidationError
from referencing import Registry
from ucp_sdk.models.schemas.shopping.checkout import Checkout
from ucp_sdk.models.schemas.shopping.checkout_complete_request import CheckoutCompleteRequest

UCP_VERSION = "2026-08-25"
SCHEMA_DIRECTORY = Path(__file__).resolve().parents[1] / "schemas"


class SchemaValidationError(ValueError):
    """The payload does not match the pinned released UCP shape."""


@lru_cache(maxsize=2)
def _validator(filename: str) -> Draft202012Validator:
    schema = json.loads((SCHEMA_DIRECTORY / filename).read_text(encoding="utf-8"))
    Draft202012Validator.check_schema(schema)
    return Draft202012Validator(
        schema,
        format_checker=FormatChecker(),
        # Registry's default retrieval raises NoSuchResource; unlike the legacy
        # jsonschema resolver it does not fetch an unknown URI from the network.
        registry=Registry(),
    )


def validate_checkout(payload: dict[str, Any]) -> None:
    """Validate a base checkout response without modifying or authenticating it."""
    try:
        _validator("checkout-response.json").validate(payload)
        Checkout.model_validate(payload)
    except (JsonSchemaValidationError, ModelValidationError):
        # Public validation errors must not echo customer or payment data.
        raise SchemaValidationError("invalid UCP checkout response") from None


def validate_complete_request(payload: dict[str, Any]) -> None:
    """Validate the completion request shape, not its spending authority."""
    try:
        _validator("checkout-complete-request.json").validate(payload)
        CheckoutCompleteRequest.model_validate(payload)
    except (JsonSchemaValidationError, ModelValidationError):
        raise SchemaValidationError("invalid UCP completion request") from None


def sample_checkout(
    checkout_id: str = "checkout-001",
    amount_minor: int = 12500,
    status: str = "ready_for_complete",
) -> dict[str, Any]:
    """One fictional unextended checkout; no real merchant or payment instrument."""
    checkout: dict[str, Any] = {
        "ucp": {
            "version": UCP_VERSION,
            "status": "success",
            "capabilities": {
                "dev.ucp.shopping.checkout": [
                    {
                        "version": UCP_VERSION,
                        "schema": "https://ucp.dev/schemas/shopping/checkout.json",
                    }
                ]
            },
            "payment_handlers": {},
        },
        "id": checkout_id,
        "status": status,
        "currency": "USD",
        "line_items": [
            {
                "id": "line-example-001",
                "item": {
                    "id": "item-example-001",
                    "title": "Fictional example reservation",
                    "price": amount_minor,
                },
                "quantity": 1,
                "totals": [
                    {"type": "subtotal", "amount": amount_minor},
                    {"type": "total", "amount": amount_minor},
                ],
            }
        ],
        "totals": [
            {"type": "subtotal", "amount": amount_minor},
            {"type": "total", "amount": amount_minor},
        ],
        "links": [
            {"type": "terms_of_service", "url": "https://merchant.example/terms"},
            {"type": "privacy_policy", "url": "https://merchant.example/privacy"},
        ],
    }
    if status == "completed":
        checkout["order"] = {
            "id": "order-example-001",
            "permalink_url": "https://merchant.example/orders/order-example-001",
        }
    return checkout


def sample_complete_request() -> dict[str, Any]:
    """The released base schema permits empty instruments; no payment is processed."""
    return {"payment": {"instruments": []}}
